# Generated by Django 3.2 on 2021-04-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210409_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
